env:
  browser: true
  es6: true
  node: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:prettier/recommended"
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    configFile: "./babel.config.js"
rules:
  indent:
    - error
    - 3
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: "off"
plugins:
  - mocha

