extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2017
env:
  es6: true
  node: true
  jasmine: true
overrides:
  - files:
      - "*.js"
    rules:
      # Exemplo de regras personalizadas para arquivos JavaScript
      semi: error # Verificar se há ponto e vírgula ausente
      indent: [error, 2] # Verificar se a indentação está com 2 espaços
      quotes: [error, "single"] # Verificar se as aspas estão usando 'single' (simples)
      no-unused-vars: error # Verificar se há variáveis não utilizadas
      no-console: warn # Mostrar um aviso quando console.log é usado
ignorePatterns:
  - "*.json"
  - "*.md"
